### ISSUE TITLE
IronSource iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

### ISSUE THREAD

**Issue by cc-setwo** [ironsource-mobile/Mediation-Demo-Apps#1]
While build unity demo app I have got an error **iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.**

As I figured out the problem is in IronSourceSDKDependencies.xml file, which uses pod Install IronSource

From the pod spec file
https://github.com/CocoaPods/Specs/blob/master/Specs/7/7/b/IronSourceSDK/7.1.5.0/IronSourceSDK.podspec.json
![IronSourceProblem](https://user-images.githubusercontent.com/20683443/116146754-842b0480-a6e7-11eb-8f88-fe0df96c045b.png)

The problem is that I have got error from bintray.com **The requested URL returned error: 403 Forbidden**
As a result I can not collect an iOS build
Please help!
Logs are attached
[IronSourcePodLog.txt](https://github.com/ironsource-mobile/Mediation-Demo-Apps/files/6380063/IronSourcePodLog.txt)

**Comment by mat-fukano** [comment]
Hey @cc-setwo, it looks like this may have correlated to the Bintray scheduled brown-out, [details here](https://status.bintray.com/incidents/kh3zbvqkvj2c).

Has your access to the 7.1.5 SDK pods been restored via pod install or does this continue to be an issue for you?

**Comment by cc-setwo** [comment]
Hello,

sorry for such long response (I was on vacation). Yea, now it is okay.
Thank you for the reply. I will close the issuse.

Kidenst regards,
Vlad.

сб, 1 мая 2021 г. в 01:28, mat-fukano ***@***.***>:

**Comment by cc-setwo** [comment]
Hello,

Yea, now it is okay.
Thank you for the reply. I will close the issue.

Kindest regards.
